PrimePark/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 path('', include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('createslot/', views.createslot, name='createslot'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
    path('spots/', views.spots, name='spots'),
    path('drivers/', views.drivers, name='drivers'),
    path('driverdashboard/', views.driverdashboard, name='driverdashboard'),
    path('reviews/<str:id>/', views.reviews, name='reviews'),
    path('reviews/', views.reviews, name='reviews'),
    path('allreviews/', views.allreviews, name='allreviews'),
    path('makepayment/', views.makepayment, name='makepayment'),
    path('bookslot/<str:id>/', views.bookslot, name='bookslot'),
    
    path('driverportfolio/<str:id>/', views.driverportfolio, name='driverportfolio'),
    path('invoice/', views.invoice, name='invoice'),
    path('geninvoice/', views.generate_invoice, name='generate_invoice'),

   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from email.policy import default
from importlib.abc import Traversable
from random import choices
import django
from django.contrib.auth.models import (AbstractBaseUser, AbstractUser,
                                      BaseUserManager)
from django.db import models

class UsersManager(BaseUserManager):
    def create_user(self, nid, password=None):
        if not nid:
            raise ValueError('Users must have an nid address')
        user = self.model(
            nid=self.normalize_email(nid),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
class Users(AbstractBaseUser):
    user_type = (
        ('R', 'Rentee'),
        ('S', 'Spot Owner'),
        ('D', 'Driver'),
    )
    nid = models.CharField("nid",max_length=30, unique=True, primary_key=True)
    name = models.CharField("name",max_length=200)
    email = models.CharField("email",max_length=200)
    password = models.CharField("password",max_length=128)
    contact = models.CharField("contact",max_length=15, null=True)
    last_login = models.DateTimeField("last_login", auto_now_add=True, null=True)
    is_owner = models.CharField("is_owner", max_length=10, choices=user_type,default='user')
    user_balance = models.IntegerField("user_balance", default=0,null=True)
    USERNAME_FIELD = 'nid'
    objects = UsersManager()
    def __str__(self):
        return self.nid

class SpotOwner(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.nid


class Rentee(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.nid

class Drivers(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    driver_id = models.CharField("driver_id",max_length=30,null=True,default=None)
    driver_area = models.CharField("driver_area",max_length=30,null=True,default="Dhaka")
    driver_about_me = models.CharField("driver_about_me",max_length=200,null=True,default="")
    driver_experience = models.CharField("driver_experience",max_length=200,null=True,default="2")
    driver_contact = models.CharField("driver_contact",max_length=15, null=True)
    
    

class Spot(models.Model):
    spot_id = models.CharField("spot_id",max_length=30, unique=True, primary_key=True)
    spot_road = models.CharField("spot_road",max_length=200)
    spot_area = models.CharField("spot_area",max_length=200)
    spot_house = models.CharField("spot_house",max_length=200)
    spot_owner = models.ForeignKey(Users, on_delete=models.CASCADE,null=True,default=None)
    spot_maps_url = models.CharField("spot_maps_url",max_length=200,null=True)
    spot_desc = models.CharField("spot_desc",max_length=200,null=True)
    spot_number = models.CharField("spot_number",max_length=200,null=True)
    spot_times = models.CharField("spot_times",max_length=200,default="")
    spot_reviews = models.CharField("spot_reviews",max_length=200,default="",null=True)
    def __str__(self):
        return self.spot_id

class TimeSlots(models.Model):
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    slot_1 = models.CharField("slot_1",max_length=200,default='9:00AM-11:00AM')
    slot_2 = models.CharField("slot_2",max_length=200,default='11:00AM-1:00PM')
    slot_3 = models.CharField("slot_3",max_length=200,default='1:00PM-3:00PM')
    slot_4 = models.CharField("slot_4",max_length=200,default='3:00PM-5:00PM')

home/forms.py
import email
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm

class UserForm(ModelForm):
    class Meta: 
        model = Users
        fields = '__all__'
class SpotForm(ModelForm):
    class Meta: 
        model = Spot
        fields = '__all__'
        

home/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user
from .models import *
from pprint import pprint
from django.core.mail import send_mail  
from PrimePark import settings  
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

# Create your views here.


def SendEmail(to_email, subject, username):
        print("Sending Email Function")
        html_template = 'home/message.html'
        subject = subject
        from_email = settings.EMAIL_HOST_USER
        to_email = to_email
        print("to_email:",to_email)
        html_message = render_to_string(html_template, { 'username': username })
        message = EmailMessage(subject, html_message, from_email, [to_email])
        message.content_subtype = 'html' # this is required because there is no plain text email message
        message.send()
        print("Email Sent")
        

def index(request):
    return render(request, 'home/index.html')


def login(request):
    if request.method == 'POST':
        nid = request.POST.get('nid')
        password = request.POST.get('password')
        
        print(nid, password)
        
        
        user = authenticate(nid=nid, password=password)
        print("User:",user)
        if user is not None:
            login_user(request, user)
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'home/login.html')

def dashboard(request):
    # print("Dashboard User:", request.user.nid)
    if request.user.is_authenticated:
        print("Dashboard User Type:", request.user.is_owner)

        return render(request, 'home/dashboard.html')
    else:
        return redirect('login')

def createslot(request):
    if request.user.is_authenticated:
        if request.user.is_owner == "S":
            if request.method == 'POST':
                print("POST:",request.POST)
                print("Creating Slot...")

                NEWSPOT = Spot.objects.create(
                    spot_id = request.POST.get('spot_id'),
                    spot_area = request.POST.get('spot_area'),
                    spot_road = request.POST.get('spot_road'),
                    spot_house = request.POST.get('spot_house'),
                    spot_number = request.POST.get('spot_number'),
                    spot_maps_url = request.POST.get('spot_maps_url'),
                    spot_desc = request.POST.get('spot_desc'),
                    spot_owner = Users.objects.get(nid=request.user.nid),
                )
                NEWSPOT.save()
                
                NEWTIME = TimeSlots.objects.create(
                    spot = NEWSPOT
                )
                NEWTIME.save()        
                print("New Spot Created")
                return redirect('spots') 
            return render(request, 'home/createslot.html')
        else: 
            return redirect('unauthorized')
    else:
        return redirect('login')

def signup(request):
    if request.method == 'POST':
        pprint(request.POST)
        user_name = request.POST.get('name')
        user_nid = request.POST.get('nid')
        user_email = request.POST.get('email')
        user_password = request.POST.get('password')
        user_contact = request.POST.get('contact')
        user_type = request.POST.get('is_owner')
        user = Users.objects.create(nid=user_nid, 
                                    password=user_password, 
                                    name=user_name, 
                                    email=user_email,
                                    contact=user_contact, 
                                    is_owner=user_type)
        user.save()
        messages.success(request, 'User created successfully')
        user.set_password(user_password)
        user.save()
        
        print("NEW USER:",user)
        #! Owner Creation Part
        if user_type == 'S':
            print("Creating Owner...")
            owner = SpotOwner.objects.create(user=user, 
                                             balance=0,
                                             )
            owner.save()
            print("Owner Created")
            return redirect('login')
        
        if user_type == 'D':
            print("Creating Driver...")
            driver = Drivers.objects.create(user=user)
            driver.save()
            print("Driver Created")
        
        if user_type == "R":
            print("Creating Renter...")
            renter = Rentee.objects.create(user=user)
            renter.save()
            print("Renter Created")
        
        
        auth_user = authenticate(nid=user_nid, password=user_password)
        login_user(request, auth_user)
        SendEmail(to_email=user_email, subject='Welcome to PrimePark', username=user_name)
        print("auth_user:",auth_user)
        return redirect('dashboard')
    else:
        return render(request, 'home/signup.html')



def logout(request):
    print('Logout User:', request.user.nid)
    logout_user(request)
    return redirect('login')

def spots(request): 
    
    ALL_SPOTS = Spot.objects.all()
    print(ALL_SPOTS)
    ALL_SPOTS = [spot for spot in ALL_SPOTS]
    ALL_TIMES = []
    for spot in ALL_SPOTS:
        print("Spot:",spot)
        slots = TimeSlots.objects.get(spot=spot)
        fields = slots._meta.get_fields()
        lst = []
        for field in fields:
            lst.append(field.value_from_object(slots))
        print("----")   
        lst = lst[2:]
        spot.spot_times = lst
        spot.save()
    context = {
        'ALL_SPOTS': ALL_SPOTS,
    }
    
    return render(request, 'home/spots.html',context=context)

def bookslot(request,id=""):
    spot = Spot.objects.get(spot_id=id)
    spot_timings = TimeSlots.objects.get(spot=spot)
    already_slots_data = []
    already_slots_data.append(spot_timings.slot_1)
    already_slots_data.append(spot_timings.slot_2)
    already_slots_data.append(spot_timings.slot_3)
    already_slots_data.append(spot_timings.slot_4)
    print("Already Slots:",already_slots_data)
    
    # print (spot.spot_slots)

    if request.method == 'POST':
        print("POST:",request.POST)
        print("Booking Slot...")
        post_request_slots = request.POST.getlist('booked_slots')
        print(post_request_slots)
        
        for i, time in enumerate(post_request_slots):
            if time in already_slots_data:
                if time == "9:00AM-11:00AM":
                    spot_timings.slot_1 = "Booked"
                    spot_timings.save()
                    already_slots_data[0] = "Booked"
                if time == "11:00AM-1:00PM":
                    spot_timings.slot_2 = "Booked"
                    spot_timings.save()
                    already_slots_data[1] = "Booked"
                if time == "1:00PM-3:00PM":
                    spot_timings.slot_3 = "Booked"
                    spot_timings.save()
                    already_slots_data[2] = "Booked"
                    
                if time == "3:00PM-5:00PM":
                    spot_timings.slot_4 = "Booked"
                    spot_timings.save()
                    already_slots_data[3] = "Booked"
        
        spot.spot_times = already_slots_data
        spot.save()
        
        print("Final Slots:",already_slots_data)
        
        
        
        
    context = {
        'id' : id,
        'spot': spot,
    }
    return render(request, 'home/bookslot.html',context=context)

def drivers(request):
    
    ALL_DRIVERS = Drivers.objects.all()
    context = {
        'ALL_DRIVERS': ALL_DRIVERS,
    }
    return render(request, 'home/drivers.html',context=context)


def unauthorized(request):
    return render(request, 'home/unauthorized.html')


def driverdashboard(request):
    print("here")
    if request.method == "POST":
        print(request.POST)
        driver = Drivers.objects.get(user=request.user)
        driver.driver_id = request.POST.get('license')
        driver.driver_area = request.POST.get('city')    
        driver.driver_about_me = request.POST.get('aboutyou')
        driver.driver_experience = request.POST.get('exp')
        driver.driver_contact = request.POST.get('contact')
        driver.save()
        print("Driver Updated")
        return redirect('driverdashboard')  
    
    driver = Drivers.objects.get(user=request.user)
    license = driver.driver_id
    area = driver.driver_area
    aboutyou = driver.driver_about_me
    expr = driver.driver_experience
    context = {
        'license': license,
        'area': area,
        'aboutyou': aboutyou,
        'expr': expr,
        'contact': driver.user.contact,
    }
    return render(request, 'home/driverdashboard.html',context=context)
        
    
    
    return render(request, 'home/driverdashboard.html')

def reviews(request,id=""):
    spot = Spot.objects.get(spot_id=id)
    
    if request.method == 'POST':
        print("POST:",request.POST)
        print("Reviewing Spot...")
        review = request.POST.get('review')
        print(review)
        existing_reviews = spot.spot_reviews
        existing_reviews += review 
        existing_reviews += "."
        spot.spot_reviews = existing_reviews
        spot.save()
        print("Spot Reviewed")
        return redirect('dashboard')
    
    context = {
        'spot': spot,
    }
    return render(request, 'home/reviews.html',context=context)

def allreviews(request):
    ALL_SPOTS = Spot.objects.all()
    context = {
        'ALL_SPOTS': ALL_SPOTS,
    }

home/templates/home/generate_invoice2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assets/custom/style.css' %}">
         
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="logo-img"></div>
    <div class="container">
        <div class="forms">
            
            <div class="form signup">
                <span class="title">Invoice Generator</span>
                 
                {% if errors is not None %}
                {{ errors }}
                {% endif %}

                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input name="days" type="text" placeholder="Days" value="30 Days" required> 
                        <i class="uil uil-user"></i>
                    </div>
                    
                    
                    <div class="input-field">
                        <input name="customer_name" type="text" placeholder="Customer Name" required>
                        <i class="uil uil-car"></i>
                    </div>
                    <div class="input-field">
                        <input name="customer_number" type="text" placeholder="Customer number" required>
                        <i class="uil uil-phone icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="customer_Address" type="text" placeholder="Customer Address" value="NaN, Dhaka" required>
                        <i class="uil uil-phone icon"></i>
                    </div>
                    
                    <hr>
                    {% comment %} Account Details {% endcomment %}
                    
                    <div class="input-field">
                        <input name="account_title" type="text" placeholder="Account Title" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_email" type="text" placeholder="Account email" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_password" type="text" placeholder="Account password" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_profile" type="text" placeholder="Account profile" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_pin" type="text" placeholder="Account pin" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_expiry" type="text" placeholder="Account expiry" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>

                    
                    <div class="input-field">
                        <input name="account_title" type="text" placeholder="Account Title" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_email" type="text" placeholder="Account email" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_password" type="text" placeholder="Account password" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_profile" type="text" placeholder="Account profile" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_pin" type="text" placeholder="Account pin" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="account_expiry" type="text" placeholder="Account expiry" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    
                    

                    
                    <div class="input-field">
                        <input name="phone" type="text" placeholder="Enter your phone number" required>
                        <i class="uil uil-phone icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="password" type="text" class="password" placeholder="Create a password" required>
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="user-select">
                        <select name="is_owner" id="id_is_owner" for = "id_is_owner" required>
                          <option value="R">Select User Type:</option>
                          <option value="S">Spot Owner</option>
                          <option value="R">Spot Rentee</option>
                          <option value="D">Driver</option>
                        </select>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="termCon">
                            <label for="termCon" class="text">I accept all the terms and conditions</label>
                        </div>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Signup">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Already a member?
                        <a href=" {% url 'login' %} " class="text login-link">Login Now</a>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'assets/custom/script.js' %}"></script>

</body>
</html>

home/templates/home/home.html
{% load static %}
{% include 'base-sidebar.html' %}

home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <title>Login 05</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Login: Car Parking Rental Management System </h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="wrap">
                        <div class="img" style="background-image: url({%static 'images/bg-1.jpg' %});"></div>
                        <div class="login-wrap p-4 p-md-5">
                            <div class="d-flex">
                                <div class="w-100">
                                    <a href="{% url 'login'%}"><button type="button"
                                            class="btn btn-outline-primary btn-lg">⠀⠀⠀Login⠀⠀⠀</button></a>
                                </div>
                                <div class="w-100">
                                    <a href="{% url 'signup'%}"><button type="button"
                                            class="btn btn-outline-warning btn-lg">⠀⠀⠀Sign up⠀⠀⠀</button></a>

                                </div>
                                <div class="w-100">
                                    <a href="{% url 'logout'%}"><button type="button"
                                            class="btn btn-outline-warning btn-lg">⠀⠀⠀Logout⠀⠀⠀</button></a>

                                </div>
                                <br><br><br>
                            </div>
                            <!--Start: Login Page -->
                            <form action="" class="signin-form" method="POST">
                                {% csrf_token %}
                                {% comment %} <div class="form-group mt-3">
                                    {% comment %} <input type="text" class="form-control" required> 
                                    <input type="text" class="form-control" name="first_name" maxlength="150"
                                        id="id_first_name" required>
                                    <label class="form-control-placeholder" for="id_first_name">First Name</label>
                                </div> {% endcomment %}
                                <div class="form-group">
                                    <input id="id_nid" class="form-control" type="text" name="nid" maxlength="200"
                                        required>
                                    <label class="form-control-placeholder" for="id_nid">NID:</label>
                                </div>
                                <div class="form-group">
                                    <input id="id_password" class="form-control" type="password" name="password"
                                        maxlength="30" required>
                                    <label class="form-control-placeholder" for="id_username">Password:</label>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary rounded submit px-3">Sign
                                        In</button>
                                </div>

                            </form>
                            <p class="text-center">Not a member? <a data-toggle="tab" href="#signup">Sign In</a></p>
                        </div>
                        <!--End: Login Page -->

                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>

</body>

</html>

home/templates/home/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assets/custom/style.css' %}">
         
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="logo-img"></div>
    <div class="container">
        <div class="forms">
            
            <div class="form signup">
                <span class="title">Registration</span>
                 
                {% if errors is not None %}
                {{ errors }}
                {% endif %}

                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input name="name" type="text" placeholder="Enter your name" required>
                        <i class="uil uil-user"></i>
                    </div>
                    <div class="input-field">
                        <input name="nid" type="text" placeholder="Enter your NID" required>
                        <i class="uil uil-car"></i>
                    </div>
                    <div class="input-field">
                        <input name="email" type="text" placeholder="Enter your email" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="phone" type="text" placeholder="Enter your phone number" required>
                        <i class="uil uil-phone icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="password" type="password" class="password" placeholder="Create a password" required>
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="user-select">
                        <select name="is_owner" id="id_is_owner" for = "id_is_owner" required>
                          <option value="R">Select User Type:</option>
                          <option value="S">Spot Owner</option>
                          <option value="R">Spot Rentee</option>
                          <option value="D">Driver</option>
                        </select>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="termCon">
                            <label for="termCon" class="text">I accept all the terms and conditions</label>
                        </div>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Signup">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Already a member?
                        <a href=" {% url 'login' %} " class="text login-link">Login Now</a>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'assets/custom/script.js' %}"></script>

</body>
</html>

home/templates/home/unauthorized.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized</title>
</head>
<body>
    <h1> You are not permitted to view this page. </h1>
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Read More</a>
</body>
</html>